website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Patient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(100))
    result = db.Column(db.String)
    probability = db.Column(db.Float)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Patient')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "users.db"
UPLOAD_FOLDER = 'static/uploads/'


def create_app():
    basedir = path.abspath(path.dirname(__file__))
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + path.join(basedir, DB_NAME)
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Patient

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from .models import Patient
from . import db
from tensorflow.keras.models import model_from_json
import cv2
import numpy as np
import os
import urllib.request

img_size = 300
label_dict = {0: 'Covid19', 1: 'Normal', 2: 'Pneumonia'}

views = Blueprint('views', __name__)

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

basedir = os.path.abspath(os.path.dirname(__file__))

model_url = 'https://github.com/Nilavan/RespAI/releases/download/model/model_weights.h5'
model_filename = model_url.split('/')[-1]

if not os.path.exists(model_filename):
    print("Downloading model...")
    urllib.request.urlretrieve(model_url, model_filename)
    print("Model downloaded!")


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        name = request.form.get('name')
        email = request.form.get('email')
        if file.filename == '':
            flash('No image selected', category='error')
            return redirect(request.url)
        elif (name == '' or email == ''):
            flash("Enter name and email id", category="error")
            return redirect(request.url)
        elif file and allowed_file(file.filename) and name != '' and email != '':
            json_file = open('model.json', 'r')
            loaded_model_json = json_file.read()
            json_file.close()
            model = model_from_json(loaded_model_json)
            model.load_weights(model_filename)
            filename = secure_filename(file.filename)
            file_stored = os.path.join(
                basedir, current_app.config['UPLOAD_FOLDER'], filename)
            file.save(file_stored)
            test_image = cv2.imread(file_stored)
            test_image = cv2.resize(test_image, (300, 300))
            test_image = test_image.astype('float32') / 255.0
            prediction = model.predict(
                np.expand_dims(test_image, axis=0))[0]
            result = np.argmax(prediction)
            label = label_dict[result]
            accuracy = float(np.max(prediction)*100.0)
            new_patient = Patient(name=name, email=email, result=label,
                                  probability=accuracy, user_id=current_user.id)
            db.session.add(new_patient)
            db.session.commit()
            flash('Patient added to database! Please verify the results',
                  category='success')
            return render_template('home.html', patient=name, email=email, filename=filename, result=label, accuracy=int(accuracy), user=current_user)
        else:
            flash('Allowed image types are -> png, jpg, jpeg', category='error')
            return redirect(request.url)

    return render_template('home.html', user=current_user)


@views.route('/display/<filename>')
def display_image(filename):
    return redirect(url_for('static', filename='uploads/' + filename), code=301)

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='styles/style.css') }}"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="col">
  <br />
  <h1 align="center">COVID-19/PNEUMONIA TESTING</h1>
  <br />
</div>
<div class="row">
  <div class="col-lg-6 col-md-5 col-sm-3 col-10 p-3">
    <form method="post" enctype="multipart/form-data">
      <div class="row">
        <label class="col" for="name" align="left">Patient Name:</label>
        <input
          class="col"
          type="text"
          name="name"
          id="name"
          placeholder="{{ patient }}"
        /><br />
      </div>
      <br />
      <div class="row">
        <label class="col" for="email" align="left">Patient's email:</label>
        <input
          class="col"
          type="email"
          name="email"
          id="email"
          placeholder="{{ email }}"
        />
      </div>
      <div class="col p-2 pt-4" align="center">
        <input
          class="btn btn-outline-info form-control-file w-100"
          id="image-selector"
          type="file"
          name="file"
          onchange="loadFile(event)"
        />
      </div>
      <div class="row m-7">
        <input
          type="submit"
          id="predict-button"
          name="button-name"
          class="col m-3 btn btn-outline-primary"
          value="Predict"
        />
        {% if result %}
        <input
          type="button"
          id="verify-button"
          name="button-name"
          class="col m-3 btn btn-outline-success"
          onclick="verify()"
          value="Verify"
        />
        <script src="https://smtpjs.com/v3/smtp.js"></script>
        <script>
          function verify() {
            let email = document
              .getElementById("email")
              .getAttribute("placeholder");
            let name = document
              .getElementById("name")
              .getAttribute("placeholder");
            let prediction = document.getElementById("result").textContent;
            let probability =
              document.getElementById("probability").textContent;
            let output =
              "Email sent to " +
              name +
              " - " +
              email +
              "\nCOVID19/Pneumonia Result: " +
              probability +
              " chance of " +
              prediction;
            document.getElementById("name").placeholder = "";
            document.getElementById("email").placeholder = "";
            <!-- "7472883f-b08d-404a-ae4e-1ff6f8a5f50f" -->
            Email.send({
              SecureToken: "3adb7480-22b9-4738-8df1-508d5c5da9d7",
              To: email,
              From: "nilavan.respai@gmail.com",
              Subject: "COVID19/Pneumonia Result",
              Body:
                "Dear " +
                name +
                ",<br><br>Your COVID19/Pneumonia test results have been verified to be " +
                prediction +
                " with a probability of " +
                probability +
                "<br><br>Regards,<br>Team RespAI",
            }).then(function (message) {
              alert(output);
              location.replace(location.origin);
            });
          }
        </script>
        {% endif %}
      </div>
    </form>
    <div class="col p-5 results">
      <p class="row">Prediction:&nbsp;<span id="result">{{ result }}</span></p>
      <p class="row">
        Probability:&nbsp;<span id="probability">{{ accuracy }}%</span>
      </p>
    </div>
  </div>
  <div class="col">
    <br />
    <h4 align="center">Selected Image</h4>
    <div class="col p-3" align="center">
      <img id="selected-image" class="img-fluid" />
      <img
        class="img-fluid"
        src="{{ url_for('views.display_image', filename=filename) }}"
        id="selected-image-placeholder"
        onerror="this.style.display = 'none'"
      />
      <script>
        var loadFile = function (event) {
          var image = document.getElementById("selected-image");
          image.src = URL.createObjectURL(event.target.files[0]);
          var placeholder = document.getElementById(
            "selected-image-placeholder"
          );
          placeholder.src = "";
        };
      </script>
    </div>
  </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <br />
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <br />
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}